version: "3.8"

services:
  front:
      container_name: front
      # image: app-dev
      build:
        context: ./front
        dockerfile: Dockerfile
      volumes:
        - ./front/src:/app/src
      ports:
        - 3000:3000
  web:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - 5450:5450
